#! /usr/bin/env python

import face_recognition
import os, sys
import pickle
from pysqlite2 import dbapi2 as sqlite3

# Open DB
groups = {}
print "Loading database..."
db = sqlite3.connect('faces.db')
cur = db.cursor()

# Read face descriptor lines, as written by face_tag script..
for tagfile in sys.argv[1:]:
    print("Loading faces from {}".format(tagfile))
    fold = os.path.dirname(tagfile)
    tagfd = open(tagfile, 'rt')
    for line in tagfd:
        # Parse as <file>: face @ <l,t,r,b>
        if not ('face @' in line):
            continue
        (file, face) = line.split(':')
        (left, top, right, bottom) = face[8:].split(',')
        loc = [(int(top),int(right),int(bottom),int(left))]
        print("    {} has face @ {}".format(file, loc[0]))
        pth = "{}/{}".format(fold, file)
        try:
            # Load each image and generate facial encoding
            img = face_recognition.load_image_file(pth)
            enc = face_recognition.face_encodings(img, loc)[0]
            cur.execute('INSERT INTO groups (id,path,left,top,right,bottom,pickled) values (?,?,?,?,?,?,?)',
                (-1, pth, loc[0][3], loc[0][0], loc[0][1], loc[0][2], pickle.dumps(enc)))
        except Exception, e:
            print("    {}: oops: {}".format(file,e))
            pass
    tagfd.close()
    db.commit()

db.close()
