#! /usr/bin/env python

import os, sys
from pysqlite2 import dbapi2 as sqlite3
import xml.etree.ElementTree as et

# Open the DB
dbfile = 'faces.db'
if len(sys.argv)>1:
    dbfile = sys.argv[1]
if not os.path.isfile(dbfile):
    print "No such file: {}".format(dbfile)
    sys.exit(1)
db = sqlite3.connect(dbfile)
cur = db.cursor()

# Load labels and groups
print "Loading labels & groups"
cur.execute('SELECT label, grp from face_groups ORDER BY label, grp')
cats = []
for row in cur:
    cat = (str(row[0]), row[1])
    cats.append(cat)

# Ensure there is a catalog file for each label & group
print "Building catalog files.."
ncnt = 0
ucnt = 0
for cat in cats:
    catname = cat[0] + '_' + str(cat[1])
    catfile = os.environ['HOME'] + '/.local/share/gthumb/catalogs/' + catname + '.catalog'
    tree = None
    fils = None
    if os.path.isfile(catfile):
        # open existing catalog, remove files
        tree = et.parse(catfile)
        root = tree.getroot()
        fils = root.find('files')
        root.remove(fils)
        fils = et.SubElement(root, 'files')
        ucnt += 1
    else:
        # Making a new catalog...
        root = et.Element('catalog')
        root.set('version', '1.0')
        tree = et.ElementTree(root)
        name = et.SubElement(root, 'name')
        name.text = catname
        fils = et.SubElement(root, 'files')
        ncnt += 1
    # Put in the files..
    fcnt = 0
    cur.execute('SELECT DISTINCT(path) from file_paths p, face_data d where p.hash = d.hash and d.grp = ?', (cat[1],))
    for row in cur:
        path = str(row[0])
        fil = et.SubElement(fils, 'file')
        fil.set('uri', 'file://' + path)
        fcnt += 1
    # Save the catalog
    tree.write(catfile, encoding="UTF-8", xml_declaration=True)
    print "Saved {} files for human {} in group {}".format(fcnt, cat[0], cat[1])

print "Updated {} catalogs, created {}".format(ucnt, ncnt)
db.close()
