#! /usr/bin/env python

import os, sys, pickle, math
import numpy
from pysqlite2 import dbapi2 as sqlite3

# Open the DB
dbfile = 'faces.db'
if len(sys.argv)>1:
    dbfile = sys.argv[1]
if not os.path.isfile(dbfile):
    print "No such file: {}".format(dbfile)
    sys.exit(1)
db = sqlite3.connect(dbfile)
cur = db.cursor()

# Unpickle every face, measure the variance on each element
print "averaging..."
avg = []
cnt = 0.0
cur.execute('SELECT pickled from groups')
for row in cur:
    enc = pickle.loads(row[0])
    if len(avg)==0:
        avg = enc
    else:
        for i in range(0,len(enc)):
            avg[i] = (cnt-1)/cnt * avg[i] + 1/cnt * enc[i]
    cnt += 1.0

print "measuring variance..."
vai = []
cnt = 0.0
cur.execute('SELECT pickled from groups')
for row in cur:
    enc = pickle.loads(row[0])
    if len(vai)==0:
        vai = [0] * len(enc)
    else:
        for i in range(0,len(enc)):
            v = (enc[i]-avg[i])**2
            vai[i] = (cnt-1)/cnt * vai[i] + 1/cnt * v
    cnt += 1.0
tot = 0.0
for i in range(0,len(vai)):
    vai[i] = math.sqrt(vai[i])
    tot += vai[i]
scale = float(len(vai))/tot
print "sum of variances: {}, scale: {}".format(tot, scale)
for i in range(0,len(vai)):
    vai[i] *= scale
cur.execute('DELETE FROM weights')
cur.execute('INSERT INTO weights (pickled) values (?)', (pickle.dumps(numpy.asarray(vai)),))
db.commit()
db.close()
